owner: tomy0000000
repo: upptime

sites:
  - name: Main Website
    url: https://tomy.me
  - name: Blog
    url: https://blog.tomy.me
  - name: CV
    url: https://cv.tomy.me

assignees:
  - tomy0000000

status-website:
  cname: upptime.tomy.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
